"""add html_link and attendees to calendar_events

Revision ID: 0dbd31a546ad
Revises: 707d1c8bbe72
Create Date: 2026-07-12 23:26:30.512897
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbd31a546ad'
down_revision: str | Sequence[str] | None = '707d1c8bbe72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('html_link', sa.String(), nullable=True))
    op.add_column('calendar_events', sa.Column('attendees', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'attendees')
    op.drop_column('calendar_events', 'html_link')
    # ### end Alembic commands ###
